
Inactive Modules:
  1) defaultenv     2) lmod

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
srun: error: m8-5-14: tasks 0-19: Exited with exit code 1
